apiVersion: apps/v1
kind: Deployment
metadata:
  name: twoge-kube-deployment
  namespace: vega-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twoge-kube
  template:
    metadata:
      labels:
        app: twoge-kube
    spec:
      containers:
      - name: twoge-kube
        image: tsmith4014/twoge-kube
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_DATABASE
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5