apiVersion: v1
kind: Service
metadata:
  name: twoge-kube-service
  namespace: vega-namespace
spec:
  selector:
    app: twoge-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP #ClusterIP if you want to expose the service only within the cluster and NodePort if you want to expose the service outside the cluster on MiniKube.  If using a cloud provider, you can use LoadBalancer.