apiVersion: v1
kind: Service
metadata:
  name: twoge-kube-service
  namespace: vega-namespace
spec:
  selector:
    app: twoge-kube
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
