apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: vega-namespace  # Add this line
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
