name: CI/CD Pipeline

on:
  push:
    branches:
      - eks-version

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_REGION: 'us-east-1'
  K8S_NAMESPACE: 'vega-namespace'
  EKS_CLUSTER_NAME: 'cpclass-eks-cluster'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Assessment_4/app
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/twoge-kube:latest

  eks_deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: configure kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: deploy to eks
        run: |
          kubectl apply -f twoge-assesment-4/kubernetes/db-deployment.yml -n vega-namespace
          kubectl apply -f twoge-assesment-4/kubernetes/db-service.yml -n vega-namespace
      - name: Delay for 15
        run: sleep 15
      - name: Deploy EKS
        run: |
          kubectl apply -f twoge-assesment-4/kubernetes/app-deployment.yml -n vega-namespace
          kubectl apply -f twoge-assesment-4/kubernetes/app-service.yml -n vega-namespace
